# Generated by Django 3.0.5 on 2020-04-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_uk', models.CharField(max_length=200, null=True, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_image', models.ImageField(blank=True, upload_to='slider', verbose_name='Backeground image')),
                ('title', models.CharField(max_length=80, verbose_name='title')),
                ('title_ru', models.CharField(max_length=80, null=True, verbose_name='title')),
                ('title_uk', models.CharField(max_length=80, null=True, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
                ('text_ru', models.TextField(null=True, verbose_name='text')),
                ('text_uk', models.TextField(null=True, verbose_name='text')),
                ('btn_link', models.URLField(default='#', verbose_name='Link')),
                ('slide_order_number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
    ]
