# Generated by Django 3.0.4 on 2020-03-14 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slide',
            new_name='Slider',
        ),
    ]
