# Generated by Django 3.0.4 on 2020-03-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'Slide', 'verbose_name_plural': 'Slides'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Slider', 'verbose_name_plural': 'Sliders'},
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='bg_image',
            field=models.ImageField(blank=True, upload_to='slider', verbose_name='Backeground image'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='btn_link',
            field=models.URLField(default='#', verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=80, verbose_name='title'),
        ),
    ]
