# Generated by Django 3.0.4 on 2020-03-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200324_1106'),
        ('home', '0002_auto_20200317_1704'),
    ]

    operations = [
    ]
