# Generated by Django 3.0.4 on 2020-03-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_merge_20200328_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={},
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='slider',
            name='bg_image',
            field=models.ImageField(blank=True, upload_to='slider', verbose_name='Backeground image'),
        ),
    ]
