# Generated by Django 3.0.5 on 2020-04-02 20:24

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200402_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='job',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='job',
            name='responsibilities',
        ),
        migrations.AddField(
            model_name='job',
            name='conditions_ru',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=500, verbose_name='Conditions'), default=list, size=None),
        ),
        migrations.AddField(
            model_name='job',
            name='conditions_uk',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=500, verbose_name='Conditions'), default=list, size=None),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements_ru',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=500, verbose_name='Requirements'), default=list, size=None),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements_uk',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=500, verbose_name='Requirements'), default=list, size=None),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities_ru',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=500, verbose_name='Responsibilities'), default=list, size=None),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities_uk',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=500, verbose_name='Responsibilities'), default=list, size=None),
        ),
    ]
