# Generated by Django 3.0.5 on 2020-04-02 19:53

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='item',
            name='characteristics_ru',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200, verbose_name='characteristics'), default=list, size=None),
        ),
        migrations.AddField(
            model_name='item',
            name='characteristics_uk',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200, verbose_name='characteristics'), default=list, size=None),
        ),
    ]
