# Generated by Django 3.0.4 on 2020-03-13 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200307_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='reviews',
        ),
        migrations.AlterField(
            model_name='item',
            name='preview_image',
            field=models.ImageField(blank=True, upload_to='category/item_preview'),
        ),
        migrations.AlterField(
            model_name='item',
            name='producer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='producer_logo',
            field=models.ImageField(blank=True, upload_to='category/producer_logo'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50, verbose_name='author name')),
                ('text', models.CharField(max_length=400, verbose_name='comment')),
                ('pub_date', models.DateTimeField(verbose_name='data published')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Item')),
            ],
        ),
    ]
