# Generated by Django 3.0.3 on 2020-03-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_website',
            field=models.URLField(blank=True, default='#'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(max_length=150),
        ),
    ]
