# Generated by Django 3.0.5 on 2020-04-02 19:38

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='conditions',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=500, verbose_name='Conditions'), size=None),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=500, verbose_name='Requirements'), size=None),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsibilities',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=500, verbose_name='Responsibilities'), size=None),
        ),
    ]
