# Generated by Django 3.0.4 on 2020-03-28 10:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200323_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_website',
            field=models.URLField(blank=True, default='#', verbose_name='Brand website'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(upload_to='logos', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='job',
            name='conditions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500, verbose_name='Conditions'), size=None),
        ),
        migrations.AlterField(
            model_name='job',
            name='position',
            field=models.CharField(max_length=300, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500, verbose_name='Requirements'), size=None),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsibilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500, verbose_name='Responsibilities'), size=None),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(max_length=150, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='service',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=400, verbose_name='Title'),
        ),
    ]
