# Generated by Django 3.0.3 on 2020-03-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200317_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='preview_image',
            field=models.ImageField(blank=True, upload_to='news'),
        ),
    ]
